name: Deploy to Heroku

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Install Heroku CLI
        run: |
          curl https://cli-assets.heroku.com/install.sh | sh

      # 1) Escribimos tus credenciales en ~/.netrc
      - name: Setup Heroku credentials
        env:
          HEROKU_API_KEY: ${{ secrets.HEROKU_API_KEY }}
        run: |
          echo "machine api.heroku.com login _ password $HEROKU_API_KEY" > ~/.netrc
          echo "machine registry.heroku.com login _ password $HEROKU_API_KEY" >> ~/.netrc
          chmod 600 ~/.netrc

      # 2) Login al Container Registry (ahora sí)
      - name: Heroku Container Registry Login
        run: heroku container:login


      # 3) Aseguramos el stack de contenedores
      - name: Set heroku stack to container
        run: heroku stack:set container -a distribuida

      # 2) Después de hacer heroku container:push y antes de heroku container:release:
      - name: Tag & Push to Docker Hub
        env:
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
        run: |
          # Etiquetamos la imagen que Heroku CLI dejó localmente
          docker tag registry.heroku.com/distribuida/web \
                     $DOCKERHUB_USERNAME/distribuida:latest
          # Empujamos a Docker Hub
          docker push $DOCKERHUB_USERNAME/distribuida:latest

      # 4) Build, Push & Release
      - name: Build, Push & Release Docker image
        run: |
          heroku container:push web    -a distribuida
          heroku container:release web -a distribuida
